[theme]
theme = "native"
[icons]
icons = "awesome5"

[[block]]
block = "memory"
format = " $mem_used / $mem_total($mem_used_percents)"
interval = 5
warning_mem = 80
critical_mem = 95
[block.theme_overrides]
idle_fg = "#E0FFFF"

[[block]]
block = "cpu"
interval = 5
format = " $icon $utilization"
[block.theme_overrides]
idle_fg = "#ff6666"

[[block]]
block = "custom"
command = ''' echo "{\"icon\":\"tux\",\"text\":\"`uname -r`\"}" '''
interval = "once"
json = true
[block.theme_overrides]
idle_fg = "#ffff00"

[[block]]
block = "uptime"
[block.theme_overrides]
idle_fg = "#FFFFFF"

[[block]]
block = "sound"
step_width = 3
[block.theme_overrides]
idle_fg = "#d70a53"

[[block]]
block = "battery"
format = " $icon $percentage $time"
[block.theme_overrides]
info_bg = "#002060"
info_fg = "#FFFFFF"

[[block]]
block = "time"
format = " $icon $timestamp.datetime(f:'%d/%m/%Y %R', l:en_US)"
timezone = "Europe/Athens"
interval = 60
[[block.click]]
button = "left"
cmd = "gsimplecal"
[block.theme_overrides]
idle_fg="#50C878"
